crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include("movie.urls")),
]

movie/urls.py
from django.urls import path
from . import views

app_name = "movie"

urlpatterns = [
    path('', views.main, name="main"),
    path('list/',views.list, name="list"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('<int:id>/',views.detail, name="detail"),
    path('<int:id>/edit/',views.edit, name="edit"),
    path('<int:id>/update/',views.update, name="update"),
    path('<int:id>/delete/',views.delete, name="delete"),
    
    ]

movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField()
    open_date = models.DateTimeField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    
    def __str__(self):
        return self.title
    
    

movie/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.

def main(request):
    return render(request, 'movie/main.html')

def list(request):
    movies = Movie.objects.all()
    return render(request, 'movie/list.html',{"movies":movies})
    
def new(request):
    return render(request, 'movie/new.html')
    
def create(request):
    title = request.POST.get("title")
    title_en = request.POST.get("title_en")
    audience = request.POST.get("audience")
    open_date = request.POST.get("open_date")
    genre = request.POST.get("genre")
    watch_grade = request.POST.get("watch_grade")
    score = request.POST.get("score")
    poster_url = request.POST.get("poster_url")
    description = request.POST.get("description")
    
    Movie.objects.create(title=title,title_en=title_en,audience=audience,
    open_date=open_date,genre=genre,watch_grade=watch_grade,score=score,
    poster_url=poster_url,description=description)
    
    return redirect('movie:list')
    
def detail(request,id):
    movie = Movie.objects.get(id=id)
    return render(request, 'movie/detail.html', {'movie':movie})

def edit(request,id):
    movie = Movie.objects.get(id=id)
    return render(request, 'movie/edit.html', {'movie':movie})
    
def update(request,id):
    movie = Movie.objects.get(id=id)
    title = request.POST.get("title")
    title_en = request.POST.get("title_en")
    audience = request.POST.get("audience")
    open_date = request.POST.get("open_date")
    genre = request.POST.get("genre")
    watch_grade = request.POST.get("watch_grade")
    score = request.POST.get("score")
    poster_url = request.POST.get("poster_url")
    description = request.POST.get("description")
    
    movie.title = title
    movie.title_en = title_en
    movie.audience = audience
    movie.open_date = open_date
    movie.genre = genre
    movie.watch_grade = watch_grade
    movie.score = score
    movie.poster_url = poster_url
    movie.description = description
    
    movie.save()
    
    return redirect("movie:detail", id)

def delete(request,id):
    movie = Movie.objects.get(id=id)
    movie.delete()
    
    return redirect("movie:list")
    
    
    

movie/templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
      <a class="navbar-brand" href="{% url 'movie:main' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'movie:list' %}">영화 목록 보기<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
        </ul>
      </div>
    </nav>
    {% block bb %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

movie/templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block bb %}
<form action="{% url 'movie:update' movie.id %}">
    <div class="card" style="width: 18rem;">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{movie.title}}</li>
        <li class="list-group-item">{{movie.title_en}}</li>
        <li class="list-group-item">{{movie.audience}}</li>
        <li class="list-group-item">{{movie.open_date}}</li>
        <li class="list-group-item">{{movie.genre}}</li>
        <li class="list-group-item">{{movie.watch_grade}}</li>
        <li class="list-group-item">{{movie.score}}</li>
        <li class="list-group-item"><img src="{{movie.poster_url}}" alt="{{movie.title}}" style="width:260px; height:300px;"></li>
        <li class="list-group-item">{{movie.description}}</li>
      </ul>
      <button type="button" class="btn btn-warning"><a href="{% url 'movie:edit' movie.id %}">수정하기</a></button>
      <button type="button" class="btn btn-danger"><a href="{% url 'movie:delete' movie.id %}">삭제</a></button>
    </div>
</form>
{% endblock %}

movie/templates/movie/edit.html
{% extends 'movie/base.html' %}
{% block bb %}
    <form action="{% url 'movie:update' movie.id %}" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="title">영화제목</label>
        <input type="text" class="form-control" id="title" name="title" value="{{movie.title}}">
      </div>
      <div class="form-group">
        <label for="title_en">영문제목</label>
        <input type="text" class="form-control" id="title_en" name="title_en" value="{{movie.title_en}}">
      </div>
      <div class="form-group">
        <label for="audience">관객</label>
        <input type="number" class="form-control" id="audience" name="audience" value="{{movie.audience}}">
      </div>
      <div class="form-group">
        <label for="open_date">개봉일</label>
        <input type="date" class="form-control" id="open_date" name="open_date" value="{{movie.open_date}}">
      </div>
      <div class="form-group">
        <label for="genre">장르</label>
        <input type="text" class="form-control" id="genre" name="genre" value="{{movie.genre}}">
      </div>
      <div class="form-group">
        <label for="watch_grade">관람등급</label>
        <input type="text" class="form-control" id="watch_grade" name="watch_grade" value="{{movie.watch_grade}}">
      </div>
      <div class="form-group">
        <label for="score">평점</label>
        <input type="number" step="0.01" class="form-control" id="score" name="score" value="{{movie.score}}">
      </div>
      <div class="form-group">
        <label for="poster_url">포스터 보기</label>
        <input type="text" class="form-control" id="poster_url" name="poster_url" value="{{movie.poster_url}}">
      </div>
      <div class="form-group">
        <label for="description">설명</label>
        <textarea rows="4" cols="50" name="description" value="{{movie.description}}"></textarea>
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

movie/templates/movie/list.html
{% extends 'movie/base.html' %}
{% block bb %}
    <a href="{% url 'movie:new' %}">새 영화 등록</a>
    <div class="container">
        <div class="row">
            {% for movie in movies %}
                <div class="card col-3" style="width: 18rem;">
                  <div class="card-body">
                    <img src="{{movie.poster_url}}" alt="{{movie.title}}" style="width:230px; height:300px;">
                    <h5 class="card-title">{{movie.title}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{movie.score}}</h6>
                    <a href="{% url 'movie:detail' movie.id %}" class="card-link">영화 정보 보기</a>
                  </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

movie/templates/movie/main.html
{% extends 'movie/base.html' %}
{% block bb %}
    <img src="https://movie-phinf.pstatic.net/20190117_136/1547688613274CTzx8_JPEG/movie_image.jpg?type=m886_590_2" style="width:100%;" ></img>
{% endblock %}

movie/templates/movie/new.html
{% extends 'movie/base.html' %}
{% block bb %}
    <form action="{% url 'movie:create' %}" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="title">영화제목</label>
        <input type="text" class="form-control" id="title" name="title">
      </div>
      <div class="form-group">
        <label for="title_en">영문제목</label>
        <input type="text" class="form-control" id="title_en" name="title_en">
      </div>
      <div class="form-group">
        <label for="audience">관객</label>
        <input type="number" class="form-control" id="audience" name="audience">
      </div>
      <div class="form-group">
        <label for="open_date">개봉일</label>
        <input type="date" class="form-control" id="open_date" name="open_date">
      </div>
      <div class="form-group">
        <label for="genre">장르</label>
        <input type="text" class="form-control" id="genre" name="genre">
      </div>
      <div class="form-group">
        <label for="watch_grade">관람등급</label>
        <input type="text" class="form-control" id="watch_grade" name="watch_grade">
      </div>
      <div class="form-group">
        <label for="score">평점</label>
        <input type="number" step="0.01" class="form-control" id="score" name="score">
      </div>
      <div class="form-group">
        <label for="poster_url">포스터 보기</label>
        <input type="text" class="form-control" id="poster_url" name="poster_url">
      </div>
      <div class="form-group">
        <label for="description">설명</label>
        <textarea rows="4" cols="50" name="description"></textarea>
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}